version: '3.8'

services:
  microservicio:
    build:
      context: ./mcsv1 # Ruta a la carpeta donde está el Dockerfile
      dockerfile: Dockerfile  # Asegúrate de que el Dockerfile se llama así
    ports:
      - "8080:8080"  # Mapea el puerto 8080 del contenedor al 8080 de tu máquina
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/microserviciodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: microserviciodb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
