name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 68.221.120.57 >> ~/.ssh/known_hosts

      - name: Update Project
        run: |
          ssh -i ~/.ssh/id_rsa carras@68.221.120.57 << 'EOF'
            echo "Esto es una prueba: $USER"
            cd /home/juancarrasquer/proyect/microservices-java
            git pull
          EOF
