name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh juancarrasquer@gmail.com@68.221.120.57 << 'EOF'
            cd /home/juancarrasquer/proyect/microservices-java
            git pull
            ./deploy.sh
          EOF
